name: Build UserScripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(build)') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: build
        path: build
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main  
    - name: Prepare Node.JS 20.x Environment
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Make userscripts
      run: |
        cd main || exit 1
        make
    - name: Move userscripts
      run: |
        cd main || exit 1
        cp build/*.js ../build/
    - name: Commit to build branch
      run: |
        cd build || exit 1
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout --orphan temp
        git add -A
        git commit -am "Auto build"
        git branch -D build
        git branch -m build
        git push -f origin build
